"""Compact help text for workstation controls and table columns."""

from __future__ import annotations


CONTROL_HELP = {
    "universe": "Symbols used for market table, correlation, and comparison panels.",
    "watchlist_preset": "Predefined symbol universes for quick workspace switching.",
    "primary_underlying": "Underlying used for surface, chain, skew, and term views.",
    "show_3d_surface": "Toggle the 3D annualized-IV surface.",
    "surface_x_axis": "Surface coordinate: strike, spot moneyness, log spot moneyness, or model call delta.",
    "show_correlations": "Use aligned daily returns from yfinance closes.",
    "show_chain": "Show normalized yfinance option quotes after quality filters.",
    "auto_refresh": "Rerun the dashboard on the selected interval.",
    "refresh_interval": "Seconds between automatic reruns.",
    "max_spread_pct": "Exclude quotes with bid-ask spread above this fraction of mid.",
    "min_open_interest": "Minimum open interest required in the chain table.",
    "min_volume": "Minimum reported contract volume required for surface and chain inputs.",
    "max_quote_age_days": "Maximum quote age for rows with provider timestamps; untimestamped rows are kept.",
    "option_price_source": "Market price used to recompute IV for surface construction.",
    "pricing_model": "Pricing model used for contract prices, residuals, and Greeks.",
    "portfolio_csv": "CSV import with symbol, expiry, strike, type, quantity, and cost columns.",
    "hedge_objective": "Portfolio optimization target used to rank deterministic hedge suggestions.",
    "show_advanced_greeks": "Show contract-level second-order Greek sensitivities in a separate table.",
}


KPI_HELP = {
    "Spot": "Latest underlying price from the active provider.",
    "ATM IV": "Nearest-strike annualized implied volatility on the fitted surface.",
    "ATM dIV": "Near-ATM IV change versus the previous matching persisted snapshot.",
    "Exp Move": "Nearest-expiry expected move in dollars, using ATM straddle when available or ATM IV otherwise.",
    "IV Rank": "Current ATM IV position within stored local snapshot history.",
    "IV Percentile": "Share of stored local ATM IV observations less than or equal to current ATM IV.",
    "Term Spread": "Back ATM IV minus front ATM IV, in volatility points.",
    "Surface Points": "Number of fitted grid points in the displayed surface.",
    "Contracts": "Valid option rows used or summarized after filtering.",
    "Median Spread": "Median option bid-ask spread divided by mid price.",
}


COLUMN_HELP = {
    "Spot": "Underlying price in dollars.",
    "30D IV": "Approximate 30-day annualized implied volatility.",
    "60D IV": "Approximate 60-day annualized implied volatility.",
    "90D IV": "Approximate 90-day annualized implied volatility.",
    "30D Rate": "Interpolated annualized risk-free rate for a 30 calendar-day maturity.",
    "30D Div Yield": "Effective dividend yield for a 30 calendar-day maturity.",
    "Action Warnings": "Upcoming splits, dividends, or other corporate actions surfaced in data warnings.",
    "Delta": "Approximate option delta, dollars of option per dollar of spot.",
    "Gamma": "Approximate delta change per dollar of spot.",
    "Theta/day": "Approximate option time decay in dollars per calendar day.",
    "Vega/1%": "Approximate option price change for a one volatility-point move.",
    "Contracts": "Count of valid option contracts in the current source.",
    "Volume": "Sum of reported option-chain contract volume.",
    "Mode": "Live, delayed, synthetic, fallback, or unavailable data mode.",
    "IV Source": "Source used for representative implied-volatility fields.",
    "type": "Call or put.",
    "expiration": "Contract expiration date.",
    "daysToExpiration": "Calendar days to expiration.",
    "strike": "Contract strike in dollars.",
    "moneyness": "Strike divided by spot.",
    "bid": "Best reported bid in dollars.",
    "ask": "Best reported ask in dollars.",
    "mid": "Strict bid/ask midpoint when the market has a positive bid and ask above bid.",
    "mark": "Provider mark when available, otherwise midpoint or last price fallback.",
    "last": "Last reported trade price in dollars.",
    "selectedMarketPrice": "Market price selected to recompute implied volatility.",
    "selectedPriceSource": "Row-level source used for the selected market price.",
    "openInterest": "Open contracts reported by the data provider.",
    "impliedVolatility": "Provider implied volatility, annualized.",
    "computedIV": "Implied volatility recomputed from the selected market price, rate, and dividend assumptions.",
    "intrinsicValue": "Immediate exercise value in dollars.",
    "timeValue": "Selected market price minus intrinsic value.",
    "carryValue": "Zero-volatility discounted value minus intrinsic value.",
    "impliedVolContribution": "BSM price contribution from implied volatility above the zero-volatility value.",
    "modelResidual": "Selected market price minus BSM model price.",
    "pricingModel": "Selected pricing model used for contract analytics.",
    "selectedModelPrice": "Theoretical price under the selected pricing model and current assumptions.",
    "selectedModelResidual": "Selected market price minus selected-model price.",
    "europeanPrice": "European BSM price using computed IV, rate, and dividend assumptions.",
    "americanPrice": "American CRR binomial price using computed IV, rate, and dividend assumptions.",
    "earlyExercisePremium": "American price minus European BSM price.",
    "earlyExerciseFlag": "Premium above one cent; useful for dividend-sensitive early-exercise review.",
    "parityViolation": "Call and put at the same expiry/strike fail the put-call parity sanity tolerance.",
    "parityError": "Observed call-minus-put price difference minus theoretical parity difference.",
    "noArbitrageViolation": "Row fails a static no-arbitrage check such as bounds, strike monotonicity, convexity, or calendar variance.",
    "noArbitrageReasons": "Pipe-separated no-arbitrage checks that flagged this contract.",
    "riskFreeRate": "Interpolated annualized risk-free rate for this contract expiry.",
    "discountFactor": "Continuously compounded discount factor for this contract expiry.",
    "forwardPrice": "Forward price implied by spot, rate, dividend yield, and expiry.",
    "forwardMoneyness": "Strike divided by forward price.",
    "logMoneyness": "Natural log of strike divided by forward price.",
    "effectiveDividendYield": "Continuous dividend yield used by BSM for this expiry, including discrete dividend adjustment.",
    "discreteDividendAmount": "Undiscounted cash dividends with ex-dates before this contract expires.",
    "quoteQuality": "Provider quote quality label such as bid_ask, stale_bid_ask, or last_only.",
    "isCrossedMarket": "Bid is greater than ask; these rows are flagged and excluded before surface fitting.",
    "isLockedMarket": "Bid equals ask with both sides positive; these rows are flagged and excluded before surface fitting.",
    "quoteAgeSeconds": "Seconds between provider quote timestamp and snapshot normalization time.",
    "bidAskSpreadPct": "Bid-ask spread divided by mid price.",
    "rho": "Approximate option price change for a one percentage-point rate move.",
    "vanna": "Delta change for a one volatility-point move.",
    "volga": "Vega/1% change for a one volatility-point move.",
    "vomma": "Same volatility-convexity Greek as volga.",
    "charm": "Delta change over one calendar day.",
    "speed": "Gamma change for a one-dollar spot move.",
    "color": "Gamma change over one calendar day.",
}


def column_help(name: str) -> str | None:
    """Return compact help text for a displayed column."""
    return COLUMN_HELP.get(name)
