alerts:
  alert_cooldown: 60
  console_alerts: true
  correlation_break_threshold: 0.3
  data_gap_threshold: 300
  email_alerts: false
  extreme_iv_threshold: 2.0
  extreme_spread_ratio: 0.2
  extreme_spread_threshold: 0.5
  file_alerts: true
  iv_spike_threshold: 0.2
  min_correlation_history: 10
  volume_spike_multiplier: 3.0
  zero_volume_threshold: 0.8
assets:
  AAPL:
    enabled: true
    max_spread: 0.05
    max_time_to_expiry: 365
    max_weight: 0.2
    min_open_interest: 20
    min_time_to_expiry: 1
    min_volume: 50
    priority: high
    sector: technology
    sub_sector: consumer_electronics
    trading_end: null
    trading_start: null
    update_frequency: 30
    var_multiplier: 2.0
  BAC:
    enabled: true
    max_spread: 0.09
    max_time_to_expiry: 365
    max_weight: 0.12
    min_open_interest: 8
    min_time_to_expiry: 1
    min_volume: 15
    priority: medium
    sector: financial
    sub_sector: banking
    trading_end: null
    trading_start: null
    update_frequency: 60
    var_multiplier: 2.0
  GME:
    enabled: true
    max_spread: 0.15
    max_time_to_expiry: 365
    max_weight: 0.05
    min_open_interest: 10
    min_time_to_expiry: 1
    min_volume: 30
    priority: medium
    sector: consumer_discretionary
    sub_sector: gaming
    trading_end: null
    trading_start: null
    update_frequency: 45
    var_multiplier: 2.0
  GOOGL:
    enabled: true
    max_spread: 0.08
    max_time_to_expiry: 365
    max_weight: 0.18
    min_open_interest: 10
    min_time_to_expiry: 1
    min_volume: 20
    priority: high
    sector: technology
    sub_sector: internet
    trading_end: null
    trading_start: null
    update_frequency: 45
    var_multiplier: 2.0
  JPM:
    enabled: true
    max_spread: 0.08
    max_time_to_expiry: 365
    max_weight: 0.15
    min_open_interest: 10
    min_time_to_expiry: 1
    min_volume: 20
    priority: medium
    sector: financial
    sub_sector: banking
    trading_end: null
    trading_start: null
    update_frequency: 60
    var_multiplier: 2.0
  MSFT:
    enabled: true
    max_spread: 0.06
    max_time_to_expiry: 365
    max_weight: 0.2
    min_open_interest: 15
    min_time_to_expiry: 1
    min_volume: 30
    priority: high
    sector: technology
    sub_sector: software
    trading_end: null
    trading_start: null
    update_frequency: 45
    var_multiplier: 2.0
  NVDA:
    enabled: true
    max_spread: 0.07
    max_time_to_expiry: 365
    max_weight: 0.15
    min_open_interest: 15
    min_time_to_expiry: 1
    min_volume: 40
    priority: high
    sector: technology
    sub_sector: semiconductors
    trading_end: null
    trading_start: null
    update_frequency: 30
    var_multiplier: 2.0
  QQQ:
    enabled: true
    max_spread: 0.03
    max_time_to_expiry: 365
    max_weight: 0.25
    min_open_interest: 40
    min_time_to_expiry: 1
    min_volume: 80
    priority: high
    sector: technology
    sub_sector: tech_etf
    trading_end: null
    trading_start: null
    update_frequency: 30
    var_multiplier: 2.0
  SPY:
    enabled: true
    max_spread: 0.02
    max_time_to_expiry: 365
    max_weight: 0.3
    min_open_interest: 50
    min_time_to_expiry: 1
    min_volume: 100
    priority: critical
    sector: broad_market
    sub_sector: large_cap_etf
    trading_end: null
    trading_start: null
    update_frequency: 15
    var_multiplier: 2.0
  TSLA:
    enabled: true
    max_spread: 0.1
    max_time_to_expiry: 365
    max_weight: 0.1
    min_open_interest: 25
    min_time_to_expiry: 1
    min_volume: 60
    priority: high
    sector: automotive
    sub_sector: electric_vehicles
    trading_end: null
    trading_start: null
    update_frequency: 30
    var_multiplier: 2.0
metadata:
  created: '2025-06-07T19:07:55.524328'
  description: Multi-asset real-time volatility system configuration
  version: '2.0'
portfolio:
  concentration_limit: 0.4
  correlation_update_frequency: 300
  correlation_window: 20
  cross_asset_enabled: true
  diversification_target: 0.8
  max_portfolio_var: 0.05
  min_correlation_pairs: 3
  rebalancing_enabled: false
  rebalancing_frequency: 86400
  rebalancing_threshold: 0.05
  signal_history_length: 100
  signal_strength_threshold: 0.7
system:
  api_rate_limit: 5
  api_retry_attempts: 3
  api_retry_delay: 1.0
  api_timeout: 30
  cache_duration: 300
  cache_enabled: true
  health_check_interval: 30
  log_backup_count: 5
  log_file_rotation: true
  log_level: INFO
  log_max_size: 100MB
  max_cache_size: 1000
  max_worker_threads: 10
  processing_timeout: 60
  queue_max_size: 1000
  real_time_enabled: true
  update_batch_size: 5
